

import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import FrameworkLayout from '@/components/FrameworkLayout';
import {ConfigProvider} from 'antd';

export const metadata: Metadata = {
  title: "Nest Framework",
  description: "Generated by zhanjian",
};

const RootLayout = function({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
    <body className="text-1xl duration-1000">
      <AntdRegistry>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#c41414',
            },
          }}
        >
        <FrameworkLayout>{children}</FrameworkLayout>
        </ConfigProvider>
      </AntdRegistry>
    </body>
  </html>
  );
}

export default RootLayout;
