redis:
    options:
      host: "121.4.92.220"
      port: 6379
      password: "q4217715"
      db: 2
    type: "single"
typeOrm:
  type: 'mysql'
  host: '121.4.92.220'
  port: 3306
  username: 'nextruoyi'
  password: 'S8nfzcSYcF7xN5bx'
  database: 'nextruoyi'
  synchronize: false
  logging: true
  connectorPackage: 'mysql'
  extra: 
    connectionLimit: 10
    acquireTimeout: 10000
    waitForConnections: true
    queueLimit: 0
    idleTimeout: 60000
    connectTimeout: 30000
  keepConnectionAlive: true
  retryDelay: 3000
  retryAttempts: 10
jwt:
  secretkey: dgijinbineknwekngnbnksndvwkenkjnkkjeiq
perm:
  router:
    whitelist: [
      { path: '/api/auth/code', method: 'GET' },
      { path: '/api/auth/login', method: 'POST' },
      { path: '/logout', method: 'POST' },
      { path: '/perm/{id}', method: 'GET' },
      { path: '/upload', method: 'POST' },
    ]
file:
  uploadPath: '/uploads' # 文件上传路径
  serverPath: '/static/uploads' # 文件服务路径